const versiculos = [
    // 1 a 20: Salmos e Confiança
    "\"O Senhor é a minha luz e a minha salvação; de quem terei medo? O Senhor é a fortaleza da minha vida; a quem temerei?\" - Salmos 27:1",
    "\"O Senhor é a minha força e o meu escudo; nele o meu coração confia, e dele recebo ajuda.\" - Salmos 28:7",
    "\"Deleite-se no Senhor, e ele atenderá aos desejos do seu coração.\" - Salmos 37:4",
    "\"Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.\" - Salmos 37:5",
    "\"O Senhor sustenta todos os que caem e levanta todos os que estão prostrados.\" - Salmos 145:14",
    "\"O choro pode durar uma noite, mas a alegria vem pela manhã.\" - Salmos 30:5",
    "\"Cria em mim, ó Deus, um coração puro, e renova dentro de mim um espírito inabalável.\" - Salmos 51:10",
    "\"Ainda que eu ande pelo vale da sombra da morte, não temerei mal nenhum, pois tu estás comigo.\" - Salmos 23:4",
    "\"Esconde-me à sombra das tuas asas, contra os malfeitores que me oprimem.\" - Salmos 17:8",
    "\"Lâmpada para os meus pés é a tua palavra e luz para o meu caminho.\" - Salmos 119:105",
    "\"O Senhor está perto dos que têm o coração quebrantado e salva os de espírito oprimido.\" - Salmos 34:18",
    "\"Grandes coisas fez o Senhor por nós, e por isso estamos alegres.\" - Salmos 126:3",
    "\"Espere no Senhor. Seja forte! Coragem! Espere no Senhor.\" - Salmos 27:14",
    "\"O Senhor guarda os simples; fui humilhado, e ele me salvou.\" - Salmos 116:6",
    "\"Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações.\" - Salmos 46:1",
    "\"A minha alma anseia e fenece pelos átrios do Senhor; o meu coração e a minha carne exultam pelo Deus vivo.\" - Salmos 84:2",
    "\"Em paz me deito e logo adormeço, pois só tu, Senhor, me fazes habitar em segurança.\" - Salmos 4:8",
    "\"Bom é dar graças ao Senhor e cantar louvores ao teu nome, ó Altíssimo.\" - Salmos 92:1",
    "\"O Senhor é misericordioso e compassivo, longânimo e grande em benignidade.\" - Salmos 103:8",
    "\"Reconhece que o Senhor é Deus! Foi ele quem nos fez, e dele somos; somos o seu povo e rebanho do seu pasto.\" - Salmos 100:3",

    // 21 a 40: Provérbios e Sabedoria
    "\"Confie no Senhor de todo o coração e não se apoie na sua própria inteligência.\" - Provérbios 3:5",
    "\"Reconheça a Deus em todos os seus caminhos, e ele endireitará as suas veredas.\" - Provérbios 3:6",
    "\"O temor do Senhor é o princípio do saber, mas os loucos desprezam a sabedoria e a instrução.\" - Provérbios 1:7",
    "\"Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as fontes da vida.\" - Provérbios 4:23",
    "\"O nome do Senhor é uma torre forte; para ela correm os justos e estão seguros.\" - Provérbios 18:10",
    "\"A resposta branda desvia o furor, mas a palavra dura suscita a ira.\" - Provérbios 15:1",
    "\"O coração alegre serve de bom remédio, mas o espírito abatido seca os ossos.\" - Provérbios 17:22",
    "\"Muitas há intenções no coração do homem, mas o desígnio do Senhor se realizará.\" - Provérbios 19:21",
    "\"Confia as tuas obras ao Senhor, e os teus pensamentos serão estabelecidos.\" - Provérbios 16:3",
    "\"O prudente vê o mal e esconde-se; mas os simples passam adiante e sofrem a pena.\" - Provérbios 22:3",
    "\"Quem guarda a sua boca guarda a sua alma, mas o que muito abre os lábios se destrói.\" - Provérbios 13:3",
    "\"A riqueza de origem vã diminui, mas quem a ajunta com o trabalho a aumenta.\" - Provérbios 13:11",
    "\"O amigo ama em todo o tempo; e para a angústia nasce o irmão.\" - Provérbios 17:17",
    "\"Melhor é o pouco com o temor do Senhor, do que um grande tesouro onde há inquietação.\" - Provérbios 15:16",
    "\"A soberba precede a ruína, e a altivez do espírito precede a queda.\" - Provérbios 16:18",
    "\"O homem planeja o seu caminho, mas o Senhor dirige os seus passos.\" - Provérbios 16:9",
    "\"Instrui o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele.\" - Provérbios 22:6",
    "\"Como águas frias para a alma cansada, assim são as boas novas de um país remoto.\" - Provérbios 25:25",
    "\"Quem encobre as suas transgressões nunca prospera; mas o que as confessa e deixa, alcançará misericórdia.\" - Provérbios 28:13",
    "\"Enganosa é a graça e vã a formosura, mas a mulher que teme ao Senhor, essa será louvada.\" - Provérbios 31:30",

    // 41 a 60: Evangelhos e Atos
    "\"Tudo posso naquele que me fortalece.\" - Filipenses 4:13",
    "\"Disse-lhe Jesus: Se podes crer, tudo é possível ao que crê.\" - Marcos 9:23",
    "\"Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.\" - Mateus 11:28",
    "\"Buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas.\" - Mateus 6:33",
    "\"Não vos aflijais, pois, com o dia de amanhã, porque o dia de amanhã cuidará de si mesmo.\" - Mateus 6:34",
    "\"Pedi, e dar-se-vos-á; buscai, e achareis; batei, e abrir-se-vos-á.\" - Mateus 7:7",
    "\"Porque onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles.\" - Mateus 18:20",
    "\"E eis que estou convosco todos os dias, até a consumação dos séculos.\" - Mateus 28:20",
    "\"O céu e a terra passarão, mas as minhas palavras não hão de passar.\" - Mateus 24:35",
    "\"Deixo-vos a paz, a minha paz vos dou; não a dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.\" - João 14:27",
    "\"Eu sou o caminho, e a verdade, e a vida. Ninguém vem ao Pai senão por mim.\" - João 14:6",
    "\"Se vós estivésseis em mim, e as minhas palavras estivessem em vós, pedireis tudo o que quiserdes, e vos será feito.\" - João 15:7",
    "\"No mundo tereis aflições, mas tende bom ânimo; venci o mundo.\" - João 16:33",
    "\"Conhecereis a verdade, e a verdade vos libertará.\" - João 8:32",
    "\"Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida.\" - João 8:12",
    "\"Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo o que nele crê não pereça, mas tenha a vida eterna.\" - João 3:16",
    "\"O ladrão não vem senão para furtar, matar e destruir; eu vim para que tenham vida e a tenham com abundância.\" - João 10:10",
    "\"Bem-aventurados os que têm fome e sede de justiça, porque eles serão fartos.\" - Mateus 5:6",
    "\"Vós sois a luz do mundo. Não se pode esconder uma cidade situada sobre um monte.\" - Mateus 5:14",
    "\"Mas recebereis a virtude do Espírito Santo, que há de vir sobre vós; e ser-me-eis testemunhas.\" - Atos 1:8",

    // 61 a 80: Epístolas e Romanos/Pedro
    "\"E sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus.\" - Romanos 8:28",
    "\"Se Deus é por nós, quem será contra nós?\" - Romanos 8:31",
    "\"Alegrem-se na esperança, sejam pacientes na tribulação, perseverem na oração.\" - Romanos 12:12",
    "\"Não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento.\" - Romanos 12:2",
    "\"Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus nosso Senhor.\" - Romanos 6:23",
    "\"Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.\" - 1 Pedro 5:7",
    "\"Humilhai-vos debaixo da potente mão de Deus, para que a seu tempo vos exalte.\" - 1 Pedro 5:6",
    "\"O Senhor não retarda a sua promessa, ainda que alguns a têm por tardia; mas é longânimo para convosco.\" - 2 Pedro 3:9",
    "\"Portanto, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo.\" - 2 Coríntios 5:17",
    "\"A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.\" - 2 Coríntios 12:9",
    "\"Porque andamos por fé e não por vista.\" - 2 Coríntios 5:7",
    "\"Onde está, ó morte, o teu aguilhão? Onde está, ó inferno, a tua vitória?\" - 1 Coríntios 15:55",
    "\"Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor.\" - 1 Coríntios 15:58",
    "\"O amor é paciente, o amor é benigno. O amor não arde em ciúmes, não se ufana, não se ensoberbece.\" - 1 Coríntios 13:4",
    "\"Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor.\" - 1 Coríntios 13:13",
    "\"Não estejais inquietos por coisa alguma; antes, em tudo, sejam os vossos pedidos conhecidos diante de Deus pela oração e súplica, com ação de graças.\" - Filipenses 4:6",
    "\"E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.\" - Filipenses 4:7",
    "\"O meu Deus suprirá todas as vossas necessidades segundo as suas riquezas em glória em Cristo Jesus.\" - Filipenses 4:19",
    "\"Portanto, quer comais, quer bebais, ou façais outra qualquer coisa, fazei tudo para a glória de Deus.\" - 1 Coríntios 10:31",
    "\"Tudo me é lícito, mas nem tudo convém; tudo me é lícito, mas nem tudo edifica.\" - 1 Coríntios 10:23",

    // 81 a 100: Efésios, Tiago e Hebreus
    "\"Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus.\" - Efésios 2:8",
    "\"Ora, àquele que é poderoso para fazer tudo muito mais abundantemente além daquilo que pedimos ou pensamos...\" - Efésios 3:20",
    "\"Sede imitadores de Deus, como filhos amados; e andai em amor, como também Cristo nos amou.\" - Efésios 5:1-2",
    "\"Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo.\" - Efésios 6:11",
    "\"Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos.\" - Filipenses 4:4",
    "\"Habite em vós a palavra de Cristo ricamente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros.\" - Colossenses 3:16",
    "\"E, tudo quanto fizerdes em palavra ou em obra, fazei tudo em nome do Senhor Jesus, dando por ele graças a Deus Pai.\" - Colossenses 3:17",
    "\"Orai sem cessar. Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco.\" - 1 Tessalonicenses 5:17-18",
    "\"Fiel é Deus, o qual vos chamou para a comunhão de seu Filho Jesus Cristo nosso Senhor.\" - 1 Coríntios 1:9",
    "\"Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.\" - 2 Timóteo 1:7",
    "\"Toda a Escritura é divinamente inspirada e proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça.\" - 2 Timóteo 3:16",
    "\"Combati o bom combate, acabei a carreira, guardei a fé.\" - 2 Timóteo 4:7",
    "\"Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não vêem.\" - Hebreus 11:1",
    "\"Jesus Cristo é o mesmo, ontem, e hoje, e eternamente.\" - Hebreus 13:8",
    "\"Cheguemos-nos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno.\" - Hebreus 4:16",
    "\"Portanto, nós também, pois que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo o peso... corramos com paciência a carreira que nos está proposta.\" - Hebreus 12:1",
    "\"Se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente, e o não lança em rosto, e ser-lhe-á dada.\" - Tiago 1:5",
    "\"Portanto, sujeitai-vos a Deus, resisti ao diabo, e ele fugirá de vós.\" - Tiago 4:7",
    "\"A oração feita por um justo pode muito em seus efeitos.\" - Tiago 5:16",
    "\"Porque toda a carne é como a erva, e toda a glória do homem como a flor da erva. Secou-se a erva, e caiu a sua flor; mas a palavra do Senhor abrange para sempre.\" - 1 Pedro 1:24-25",

    // 101 a 120: Antigo Testamento e Profetas
    "\"Não to mandei eu? Esforça-te, e tem bom ânimo; não temas, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andares.\" - Josué 1:9",
    "\"Escolhei hoje a quem servireis... porém eu e a minha casa serviremos ao Senhor.\" - Josué 24:15",
    "\"O Senhor te abençoará e te guardará; o Senhor faça resplandecer o seu rosto sobre ti e tenha misericórdia de ti.\" - Números 6:24-25",
    "\"O Senhor levante sobre ti o seu rosto e te dê a paz.\" - Números 6:26",
    "\"Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o Senhor; pensamentos de paz, e não de mal, para vos dar o fim que esperais.\" - Jeremias 29:11",
    "\"Clama a mim, e responder-to-ei, e anunciar-to-ei coisas grandes e firmes que não sabes.\" - Jeremias 33:3",
    "\"As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim.\" - Lamentações 3:22",
    "\"Novas são cada manhã; grande é a tua fidelidade.\" - Lamentações 3:23",
    "\"Buscai o Senhor enquanto se pode achar, invocai-o enquanto está perto.\" - Isaías 55:6",
    "\"Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias; correrão, e não se cansarão; caminharão, e não se fatigarão.\" - Isaías 40:31",
    "\"Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.\" - Isaías 41:10",
    "\"Quando passares pelas águas estarei contigo, e quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti.\" - Isaías 43:2",
    "\"Certamente ele tomou sobre si as nossas enfermidades, e as nossas dores levou sobre si.\" - Isaías 53:4",
    "\"O Espírito do Senhor Deus está sobre mim, porque o Senhor me ungiu para pregar boas novas aos mansos.\" - Isaías 61:1",
    "\"Ainda que a figueira não floresça, nem haja fruto na vide; ainda que o produto da oliveira falhe... todavia eu me alegrarei no Senhor, exultarei no Deus da minha salvação.\" - Habacuque 3:17-18",
    "\"Porque um menino nos nasceu, um filho se nos deu, e o principado está sobre os seus ombros; e o seu nome será Maravilhoso, Conselheiro, Deus Forte, Pai da Eternidade, Príncipe da Paz.\" - Isaías 9:6",
    "\"O Senhor é bom, uma fortaleza no dia da angústia; e conhece os que confiam nele.\" - Naum 1:7",
    "\"Alegrai-vos vós, filhos de Sião, regozijai-vos no Senhor vosso Deus.\" - Joel 2:23",
    "\"E acontecerá que todo o que invocar o nome do Senhor será salvo.\" - Joel 2:32",
    "\"Buscai a justiça, buscai a mansidão; porventura sereis abrigados no dia da ira do Senhor.\" - Sofonias 2:3",

    // 121 a 140: Salmos, Provérbios e Jeremias
    "\"Cantai ao Senhor um cântico novo, porque ele tem feito maravilhas.\" - Salmos 98:1",
    "\"Sirvam ao Senhor com alegria; apresentem-se diante dele com cântico jubiloso.\" - Salmos 100:2",
    "\"Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o seu santo nome.\" - Salmos 103:1",
    "\"Louvem o nome do Senhor, pois só o seu nome é exaltação suprema; a sua glória está acima da terra e dos céus.\" - Salmos 148:13",
    "\"Tudo o que tem fôlego louve ao Senhor. Louvai ao Senhor!\" - Salmos 150:6",
    "\"O temor do Senhor prolonga os dias, mas os anos dos ímpios serão abreviados.\" - Provérbios 10:27",
    "\"A bênção do Senhor é que enriquece; e não traz consigo dores.\" - Provérbios 10:22",
    "\"Onde não há visão, o povo se desvia, mas o que guarda a lei, esse é bem-aventurado.\" - Provérbios 29:18",
    "\"Enganador é o coração, mais do que todas as coisas, e perverso; quem o conhecerá?\" - Jeremias 17:9",
    "\"Eu, o Senhor, esquadrinho a mente, eu provo os corações; e isto para dar a cada um segundo os seus caminhos e segundo o fruto das suas ações.\" - Jeremias 17:10",
    "\"Curam a ferida do meu povo superficialmente, dizendo: Paz, paz; quando não há paz.\" - Jeremias 6:14",
    "\"Pois eu bem sei os planos que tenho para vos prosperar...\" - Jeremias 29:11",
    "\"A ti, ó Senhor, levantarei a minha alma.\" - Salmos 25:1",
    "\"Mostra-me, Senhor, os teus caminhos, ensina-me as tuas veredas.\" - Salmos 25:4",
    "\"Guarda a minha alma, e livra-me; não me deixes confundido, porque confiei em ti.\" - Salmos 25:20",
    "\"Uma coisa aquisitei do Senhor, e a buscarei: que possa habitar na casa do Senhor todos os dias da minha vida.\" - Salmos 27:4",
    "\"O Senhor é a minha força e o meu escudo; nele o meu coração confia...\" - Salmos 28:7",
    "\"Dai ao Senhor, ó filhos dos poderosos, dai ao Senhor glória e força.\" - Salmos 29:1",
    "\"Em tuas mãos cometo o meu espírito; tu me remiste, Senhor, Deus da verdade.\" - Salmos 31:5",
    "\"Quão grande é a tua bondade, que guardaste para os que te temem...\" - Salmos 31:19",

    // 141 a 160: Salmos Contínuos
    "\"Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto.\" - Salmos 32:1",
    "\"A palavra do Senhor é reta, e todas as suas obras são fiéis.\" - Salmos 33:4",
    "\"Provem e vejam que o Senhor é bom. Bem-aventurado o homem que nele se refugia!\" - Salmos 34:8",
    "\"Muitos são os sofrimentos do justo, mas o Senhor de todos os livra.\" - Salmos 34:19",
    "\"Porque contigo está a fonte da vida; na tua luz vemos a luz.\" - Salmos 36:9",
    "\"Descansa no Senhor e espera nele; não te indignes por causa daqueles que prosperam em seu caminho...\" - Salmos 37:7",
    "\"Os passos de um homem bom são firmados pelo Senhor, e ele deleita-se no seu caminho.\" - Salmos 37:23",
    "\"Eu fui moço, e agora sou velho; mas nunca vi desamparado o justo, nem a sua semente a mendigar o pão.\" - Salmos 37:25",
    "\"A salvação dos justos vem do Senhor; ele é a sua fortaleza no tempo da angústia.\" - Salmos 37:39",
    "\"Esperei com paciência no Senhor, e ele se inclinou para mim, e ouviu o meu clamor.\" - Salmos 40:1",
    "\"Como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus!\" - Salmos 42:1",
    "\"Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus...\" - Salmos 42:5",
    "\"Envia a tua luz e a tua verdade; para que me guiem e me levem ao teu santo monte...\" - Salmos 43:3",
    "\"Deus é o nosso refúgio e fortaleza, socorro bem presente na tribulação.\" - Salmos 46:1",
    "\"Aquietai-vos, e anunciai que eu sou Deus; serei exaltado entre as nações, serei exaltado sobre a terra.\" - Salmos 46:10",
    "\"Tem misericórdia de mim, ó Deus, segundo a tua benignidade; segundo a multidão das tuas misericórdias apaga as minhas transgressões.\" - Salmos 51:1",
    "\"Lança o teu cuidado sobre o Senhor, e ele te sustentará; não permitirá jamais que o justo seja abalado.\" - Salmos 55:22",
    "\"Em Deus louvarei a sua palavra; em Deus tenho posto a minha confiança; não temerei o que me possa fazer a carne.\" - Salmos 56:4",
    "\"Desde os confins da terra clamo a ti, com o coração desfalecido. Guia-me à rocha que é alta para mim.\" - Salmos 61:2",
    "\"Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida; e habitarei na casa do Senhor por longos dias.\" - Salmos 23:6",

    // 161 a 180: Salmos Contínuos 2
    "\"Ouve, ó Deus, o meu clamor; atende à minha oração.\" - Salmos 61:1",
    "\"A minha alma tem sede de ti; a minha carne te deseja em uma terra árida, seca e sem água.\" - Salmos 63:1",
    "\"Porque a tua benignidade é melhor do que a vida; os meus lábios te louvarão.\" - Salmos 63:3",
    "\"Bendito seja Deus, que não rejeitou a minha oração, nem desviou de mim a sua benignidade.\" - Salmos 66:20",
    "\"Deus tenha misericórdia de nós e nos abençoe; e faça resplandecer o seu rosto sobre nós.\" - Salmos 67:1",
    "\"Bendito seja o Senhor, que de dia em dia nos carrega de benefícios; o Deus que é a nossa salvação.\" - Salmos 68:19",
    "\"Tu és a minha esperança, Senhor Deus, a minha confiança desde a minha mocidade.\" - Salmos 71:5",
    "\"O meu corpo e o meu coração desfalecem; mas Deus é a fortaleza do meu coração, e a minha porção para sempre.\" - Salmos 73:26",
    "\"Portanto, lembrarei das obras do Senhor; sim, lembrarei das tuas maravilhas da antiguidade.\" - Salmos 77:11",
    "\"Dá ouvidos, povo meu, à minha lei; inclinai os vossos ouvidos às palavras da minha boca.\" - Salmos 78:1",
    "\"Se o Senhor não edificar a casa, em vão trabalham os que a edificam; se o Senhor não guardar a cidade, em vão vigia a sentinela.\" - Salmos 127:1",
    "\"Eis que os filhos são herança do Senhor, e o fruto do ventre o seu galardão.\" - Salmos 127:3",
    "\"Bem-aventurado todos os que temem ao Senhor e andam nos seus caminhos.\" - Salmos 128:1",
    "\"Oh! Quão bom e quão suave é que os irmãos vivam em união!\" - Salmos 133:1",
    "\"Louvai ao Senhor, porque o Senhor é bom; cantai louvores ao seu nome, porque é gracioso.\" - Salmos 135:3",
    "\"A tua misericórdia, ó Deus, dura para sempre; não desampares as obras das tuas mãos.\" - Salmos 138:8",
    "\"Senhor, tu me tens sondado, e me conheces.\" - Salmos 139:1",
    "\"Eu te louvarei, porque de um modo assombroso e tão maravilhoso fui feito; maravilhosas são as tuas obras...\" - Salmos 139:14",
    "\"Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece os meus pensamentos.\" - Salmos 139:23",
    "\"Ó Senhor, a ti clamo; apressa-te a acudir-me; escuta a minha voz quando eu clamar a ti.\" - Salmos 141:1",

    // 181 a 200: Fim do primeiro bloco de Salmos/Provérbios
    "\"Com a minha voz clamei ao Senhor; com a minha voz fiz ao Senhor a minha súplica.\" - Salmos 142:1",
    "\"Ensina-me a fazer a tua vontade, pois tu és o meu Deus; o teu Espírito seja bom; guie-me à terra da retidão.\" - Salmos 143:10",
    "\"O Senhor é fiel em todas as suas palavras, e santo em todas as suas obras.\" - Salmos 145:13",
    "\"O Senhor abençoa os presos; o Senhor abre os olhos aos cegos; o Senhor levanta os abatidos; o Senhor ama os justos.\" - Salmos 146:7-8",
    "\"Louvai ao Senhor, porque é bom cantar louvores ao nosso Deus; porque é agradável, e o louvor é decoroso.\" - Salmos 147:1",
    "\"Ele envia a sua palavra à terra, e a sua palavra corre velozmente.\" - Salmos 147:15",
    "\"Louvem o nome do Senhor, pois só o seu nome é exaltado...\" - Salmos 148:13",
    "\"Porque o Senhor se agrada do seu povo; ele enaltecerá os mansos com a salvação.\" - Salmos 149:4",
    "\"Louvai a Deus no seu santuário; louvai-o no firmamento do seu poder.\" - Salmos 150:1",
    "\"O temor do Senhor aumenta os dias, mas os anos dos ímpios serão abreviados.\" - Provérbios 10:27",
    "\"A esperança dos justos é alegria, mas a expectação dos ímpios perecerá.\" - Provérbios 10:28",
    "\"O caminho do Senhor é fortaleza para os íntegros, mas a destruição será para os que praticam a iniquidade.\" - Provérbios 10:29",
    "\"Com a soberba vem também a ignomínia; mas com os humildes está a sabedoria.\" - Provérbios 11:2",
    "\"A integridade dos sinceros os guiará, mas a perversidade dos desleais os destruirá.\" - Provérbios 11:3",
    "\"O que anda como mexeriqueiro segreda os segredos, mas o que é fiel de espírito encobre o negócio.\" - Provérbios 11:13",
    "\"A alma generosa prosperará, e aquele que rega também será regado.\" - Provérbios 11:25",
    "\"O que confia nas suas riquezas cairá, mas os justos florecerão como a folhagem verde.\" - Provérbios 11:28",
    "\"O homem bom alcança o favor do Senhor, mas ao homem de maus desígnios ele condena.\" - Provérbios 12:2",
    "\"A coroa do homem virtuoso é a sua mulher, mas a que procede vergonhosamente é como podridão nos seus ossos.\" - Provérbios 12:4",
    "\"Os pensamentos dos justos são retos, mas os conselhos dos ímpios são engano.\" - Provérbios 12:5",

    // 201 a 230: Sequência de Provérbios
    "\"O ímpio é derribado e perece, mas a casa dos justos permanecerá firme.\" - Provérbios 12:7",
    "\"A insensatez está ligada ao coração da criança, mas a vara da correção a espantará dela.\" - Provérbios 22:15",
    "\"O prudente oculta o conhecimento, mas o coração dos tolos proclama a estultícia.\" - Provérbios 12:23",
    "\"A ansiedade no coração do homem o abate, mas a boa palavra o alegra.\" - Provérbios 12:25",
    "\"O filho sábio atenta para a instrução do pai, mas o escarnecedor não ouve a repreensão.\" - Provérbios 13:1",
    "\"A riqueza obtida com vaidade diminuirá, mas quem a ajunta com o trabalho a aumentará.\" - Provérbios 13:11",
    "\"A esperança adiada entristece o coração, mas o desejo cumprido é árvore de vida.\" - Provérbios 13:12",
    "\"Todo o homem prudente age com conhecimento, mas o tolo espalha a insensatez.\" - Provérbios 13:16",
    "\"Quem anda com os sábios será sábio, mas o companheiro dos tolos será destruído.\" - Provérbios 13:20",
    "\"O homem de bem deixa uma herança aos filhos dos seus filhos, mas a riqueza do pecador está reservada para o justo.\" - Provérbios 13:22",
    "\"O que poupa a vara aborrece a seu filho, mas o que o ama, a seu tempo o castiga.\" - Provérbios 13:24",
    "\"O justo come até fartar-se, mas o ventre dos ímpios passa necessidade.\" - Provérbios 13:25",
    "\"Toda a mulher sábia edifica a sua casa; mas a tola a derruba com as suas mãos.\" - Provérbios 14:1",
    "\"O que anda na sua retidão teme ao Senhor, mas o que se desvia dos seus caminhos o despreza.\" - Provérbios 14:2",
    "\"Na boca do tolo está a vara da soberba, mas os lábios dos sábios os guardam.\" - Provérbios 14:3",
    "\"A testemunha verdadeira não mentirá, mas a testemunha falsa se expõe a mentiras.\" - Provérbios 14:5",
    "\"A sabedoria do prudente é entender o seu caminho, mas a estultícia dos tolos é engano.\" - Provérbios 14:8",
    "\"O coração conhece a sua própria amargura, e o estranho não se intromete na sua alegria.\" - Provérbios 14:10",
    "\"A casa dos ímpios se desfará, mas a tenda dos retos florescerá.\" - Provérbios 14:11",
    "\"Há caminho que ao homem parece direito, mas o fim dele são os caminhos da morte.\" - Provérbios 14:12",
    "\"O simples crê em cada palavra, mas o prudente atenta para os seus passos.\" - Provérbios 14:15",
    "\"O homem iracundo faz loucuras, e o homem cheio de malícias é odiado.\" - Provérbios 14:17",
    "\"Os simples herdam a tolice, mas os prudentes coroam-se de conhecimento.\" - Provérbios 14:18",
    "\"Erram os que trabalham o mal; mas haverá misericórdia e verdade para os que trabalham o bem.\" - Provérbios 14:22",
    "\"Na multidão de trabalho há proveito, mas a palavra dos lábios traz apenas pobreza.\" - Provérbios 14:23",
    "\"A coroa dos sábios é a sua riqueza, mas a estultícia dos tolos não passa de estultícia.\" - Provérbios 14:24",
    "\"A testemunha verdadeira livra as almas, mas o que respira mentiras é engano.\" - Provérbios 14:25",
    "\"No temor do Senhor há forte segurança, e ele será um refúgio para os seus filhos.\" - Provérbios 14:26",
    "\"O temor do Senhor é a fonte de vida, para desviar dos laços da morte.\" - Provérbios 14:27",
    "\"Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.\" - Salmos 119:105",

    // 231 a 260: Mais Provérbios e Sabedoria Prática
    "\"Examinais as Escrituras, porque julgueis ter nelas a vida eterna, e são elas mesmas que testificam de mim.\" - João 5:39",
    "\"Toda a Escritura é divinamente inspirada e proveitosa para ensinar, para redarguir, para corrigir, para instruir em justiça.\" - 2 Timóteo 3:16",
    "\"Portanto, ide, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo.\" - Mateus 28:19",
    "\"E não vos embriagueis com vinho, em que há contenda, mas enchei-vos do Espírito.\" - Efésios 5:18",
    "\"Falando entre vós em salmos, e hinos, e cânticos espirituais; cantando e salmodiando ao Senhor no vosso coração.\" - Efésios 5:19",
    "\"Dando sempre graças por tudo a nosso Deus e Pai, em nome de nosso Senhor Jesus Cristo.\" - Efésios 5:20",
    "\"Sujeitando-vos uns aos outros no temor de Deus.\" - Efésios 5:21",
    "\"Vós, maridos, amai vossas mulheres, como também Cristo amou a igreja, e a si mesmo se entregou por ela.\" - Efésios 5:25",
    "\"Vós, filhos, obedeceis a vossos pais no Senhor, porque isto é justo.\" - Efésios 6:1",
    "\"Honra a teu pai e a tua mãe (que é o primeiro mandamento com promessa).\" - Efésios 6:2",
    "\"Para que te vá bem, e vivas muito tempo sobre a terra.\" - Efésios 6:3",
    "\"E vós, pais, não provoqueis à ira a vossos filhos, mas criai-os na doutrina e admoestação do Senhor.\" - Efésios 6:4",
    "\"Servos, obedeceis a vossos senhores segundo a carne, com temor e tremor, na simplicidade de vosso coração, como a Cristo.\" - Efésios 6:5",
    "\"Sabendo que cada um, se fizer algum bem, receberá isso do Senhor, seja servo seja livre.\" - Efésios 6:8",
    "\"E vós, senhores, fazei o mesmo para com eles, deixando as ameaças, sabendo que o Senhor deles e vosso está no céu, e que para com ele não há acepção de pessoas.\" - Efésios 6:9",
    "\"No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder.\" - Efésios 6:10",
    "\"Para que possais resistir no dia mau e, havendo feito tudo, ficar firmes.\" - Efésios 6:13",
    "\"Estai, pois, firmes, tendo cingidos os vossos lombos com a verdade, e vestidos com a couraça da justiça.\" - Efésios 6:14",
    "\"E calçados os pés na preparação do evangelho da paz.\" - Efésios 6:15",
    "\"Tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno.\" - Efésios 6:16",
    "\"Tomai também o capacete da salvação, e a espada do Espírito, que é a palavra de Deus.\" - Efésios 6:17",
    "\"Orando em todo o tempo com toda a oração e súplica no Espírito, e vigiando isto mesmo com toda a perseverança e súplica por todos os santos.\" - Efésios 6:18",
    "\"E por mim, para que me seja dada, no abrir da minha boca, a palavra com confiança, para fazer notório o mistério do evangelho.\" - Efésios 6:19",
    "\"Pelo qual sou embaixador em cadeias; para que dele possa falar ousadamente, como devo falar.\" - Efésios 6:20",
    "\"Ora, para que vós também saibais dos meus negócios, e o que eu faço, Tíquico, irmão amado e fiel ministro no Senhor, vos notificará tudo.\" - Efésios 6:21",
    "\"O qual o enviei para o mesmo fim, para que saibais do nosso estado, e ele console os vossos corações.\" - Efésios 6:22",
    "\"Paz seja com os irmãos, e amor com fé da parte de Deus Pai e do Senhor Jesus Cristo.\" - Efésios 6:23",
    "\"A graça seja com todos os que amam a nosso Senhor Jesus Cristo em sinceridade. Amém.\" - Efésios 6:24",
    "\"O prudente encobre a falta, mas o que a traz constantemente à baila separa os melhores amigos.\" - Provérbios 17:9",
    "\"A repreensão penetra mais no prudente do que cem açoites no insensato.\" - Provérbios 17:10",

    // 261 a 290: Complementos de Provérbios e Eclesiastes
    "\"O que retém as suas palavras tem o conhecimento, e o homem de espírito frio é de excelente entendimento.\" - Provérbios 17:27",
    "\"Até o tolo, quando cala, é reputado por sábio; e o que fechar os seus lábios, por entendido.\" - Provérbios 17:28",
    "\"Torre fortificada é o nome do Senhor; para ela corre o justo e está seguro.\" - Provérbios 18:10",
    "\"As riquezas do rico são a sua cidade fortificada, e como uma alta muralha na sua imaginação.\" - Provérbios 18:11",
    "\"Antes da ruína ergue-se o coração do homem, e antes da honra vai a humildade.\" - Provérbios 18:12",
    "\"O que responde antes de ouvir comete estultícia e vergonha.\" - Provérbios 18:13",
    "\"O espírito do homem sustenta a sua enfermidade, mas ao espírito abatido, quem o suportará?\" - Provérbios 18:14",
    "\"O coração do entendido adquire o conhecimento, e o ouvido dos sábios busca a ciência.\" - Provérbios 18:15",
    "\"A morte e a vida estão no poder da língua; e aquele que a ama comerá do seu fruto.\" - Provérbios 18:21",
    "\"O homem que tem amigos deve mostrar-se amigo, mas há um amigo mais chegado do que um irmão.\" - Provérbios 18:24",
    "\"Melhor é o pobre que anda na sua integridade do que o perverso de lábios e tolo.\" - Provérbios 19:1",
    "\"A insensatez do homem perverte o seu caminho, e o seu coração se irá contra o Senhor.\" - Provérbios 19:3",
    "\"As riquezas acrescentam muitos amigos, mas o pobre do seu amigo é separado.\" - Provérbios 19:4",
    "\"A testemunha falsa não ficará impune, e o que respira mentiras não escapará.\" - Provérbios 19:5",
    "\"Muitos imploram o favor do príncipe, e cada um é amigo do homem que dá presentes.\" - Provérbios 19:6",
    "\"Todos os irmãos do pobre o odiam; quanto mais os seus amigos se afastarão dele! Ele os busca com palavras, mas eles já se têm ido.\" - Provérbios 19:7",
    "\"O que adquire sabedoria ama a sua alma; o que guarda a inteligência achará o bem.\" - Provérbios 19:8",
    "\"A testemunha falsa não ficará impune, e o que respira mentiras perecerá.\" - Provérbios 19:9",
    "\"Não convém a delícia ao tolo; quanto menos ao servo dominar sobre os príncipes!\" - Provérbios 19:10",
    "\"A discrição do homem o faz ser longânimo, e a sua glória é passar por alto a transgressão.\" - Provérbios 19:11",
    "\"Como o rugido do leão é a indignação do rei, mas a sua graça é como o orvalho sobre a erva.\" - Provérbios 19:12",
    "\"O filho tolo é a desgraça do pai, e as contendas da mulher são como uma goteira contínua.\" - Provérbios 19:13",
    "\"A casa e os bens são herança dos pais; mas do Senhor vem a mulher prudente.\" - Provérbios 19:14",
    "\"A preguiça faz cair em profundo sono, e o ocioso padecerá fome.\" - Provérbios 19:15",
    "\"O que guarda o mandamento guarda a sua alma; mas o que desprezar os seus caminhos morrerá.\" - Provérbios 19:16",
    "\"Ao Senhor empresta o que se compadece do pobre, e ele lhe pagará o seu benefício.\" - Provérbios 19:17",
    "\"Castiga a teu filho, enquanto há esperança, mas não te estribes para o matar.\" - Provérbios 19:18",
    "\"O homem de grande indignação deve sofrer a pena; porque, se tu o livrares, de novo terás de fazê-lo.\" - Provérbios 19:19",
    "\"Ouve o conselho, e recebe a instrução, para que sejas sábio nos teus dias dianteiros.\" - Provérbios 19:20",
    "\"Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu.\" - Eclesiastes 3:1",

    // 291 a 320: Eclesiastes e Salmos de Transição
    "\"Há tempo de nascer, e tempo de morrer; tempo de plantar, e tempo de arrancar o que foi plantado.\" - Eclesiastes 3:2",
    "\"Tempo de matar, e tempo de curar; tempo de derrubar, e tempo de edificar.\" - Eclesiastes 3:3",
    "\"Tempo de chorar, e tempo de rir; tempo de prantear, e tempo de dançar.\" - Eclesiastes 3:4",
    "\"Tempo de espalhar pedras, e tempo de ajuntar pedras; tempo de abraçar, e tempo de afastar-se de abraçar.\" - Eclesiastes 3:5",
    "\"Tempo de buscar, e tempo de perder; tempo de guardar, e tempo de deitar fora.\" - Eclesiastes 3:6",
    "\"Tempo de rasgar, e tempo de coser; tempo de calar, e tempo de falar.\" - Eclesiastes 3:7",
    "\"Tempo de amar, e tempo de odiar; tempo de guerra, e tempo de paz.\" - Eclesiastes 3:8",
    "\"Que proveito tem o trabalhador naquilo em que trabalha?\" - Eclesiastes 3:9",
    "\"Tenho visto o trabalho que Deus deu aos filhos dos homens, para com ele os exercitarem.\" - Eclesiastes 3:10",
    "\"Tudo fez formoso a seu tempo; também pôs o mundo no coração deles, sem que o homem possa descobrir a obra que Deus fez desde o princípio até ao fim.\" - Eclesiastes 3:11",
    "\"Sei que não há coisa melhor para eles do que alegrarem-se e fazerem o bem na sua vida.\" - Eclesiastes 3:12",
    "\"E também que todo o homem coma e beba, e goze do bem de todo o seu trabalho; isto é um dom de Deus.\" - Eclesiastes 3:13",
    "\"Eu sei que tudo quanto Deus faz durará eternamente; nada se lhe deve acrescentar, e nada se lhe deve tirar; e isto faz Deus para que os homens o temam diante dele.\" - Eclesiastes 3:14",
    "\"O que é já foi, e o que há de ser, também já foi; e Deus requer o passado.\" - Eclesiastes 3:15",
    "\"Alegrai-vos no Senhor, ó vós justos, pois aos retos convém o louvor.\" - Salmos 33:1",
    "\"Louvai ao Senhor com harpa; cantai a louvores a ele com o saltério de dez cordas.\" - Salmos 33:2",
    "\"Cantai-lhe um cântico novo; tange com habilidade e com júbilo.\" - Salmos 33:3",
    "\"Porque a palavra do Senhor é reta, e todas as suas obras são fiéis.\" - Salmos 33:4",
    "\"Ele ama a justiça e o juízo; a terra está cheia da bondade do Senhor.\" - Salmos 33:5",
    "\"Pela palavra do Senhor foram feitos os céus; e todo o exército deles pelo espírito da sua boca.\" - Salmos 33:6",
    "\"Ele ajunta as águas do mar como num montón; põe os abismos em depósitos.\" - Salmos 33:7",
    "\"Tema toda a terra ao Senhor; temam-no todos os moradores do mundo.\" - Salmos 33:8",
    "\"Porque ele falou, e tudo foi feito; ele mandou, e logo apareceu.\" - Salmos 33:9",
    "\"O Senhor anula o conselho das nações, frustra os pensamentos dos povos.\" - Salmos 33:10",
    "\"O conselho do Senhor permanece para sempre; os pensamentos do seu coração de geração em geração.\" - Salmos 33:11",
    "\"Bem-aventurada é a nação cujo Deus é o Senhor, e o povo ao qual escolheu para sua herança.\" - Salmos 33:12",
    "\"O Senhor olha desde os céus e vê a todos os filhos dos homens.\" - Salmos 33:13",
    "\"Do lugar da sua habitação atenta sobre todos os moradores da terra.\" - Salmos 33:14",
    "\"Ele forma o coração de todos eles, e atenta para todas as suas obras.\" - Salmos 33:15",
    "\"O rei não se salva com a multidão do exército, nem o valente se livra pela muita força.\" - Salmos 33:16",

    // 321 a 350: Salmos 33 e Provérbios Finais
    "\"O cavalo é falácia para a segurança; não livra ninguém com a sua grande força.\" - Salmos 33:17",
    "\"Eis que os olhos do Senhor estão sobre os que o temem, sobre os que esperam na sua misericórdia;\" - Salmos 33:18",
    "\"Para livrar a suas almas da morte, e para as manter vivas na fome.\" - Salmos 33:19",
    "\"A nossa alma espera no Senhor; ele é o nosso auxílio e o nosso escudo.\" - Salmos 33:20",
    "\"Nele, pois, se alegra o nosso coração; porquanto temos confiado no seu santo nome.\" - Salmos 33:21",
    "\"Seja a tua misericórdia, ó Senhor, sobre nós, como em ti esperamos.\" - Salmos 33:22",
    "\"O coração do rei está na mão do qual o Senhor ri; como rios de água, assim o inclina a tudo o que quer.\" - Provérbios 21:1",
    "\"Todo caminho do homem é reto aos seus olhos, pero o Senhor pesa os corações.\" - Provérbios 21:2",
    "\"Fazer justiça e juízo é mais aceitável ao Senhor do que sacrifício.\" - Provérbios 21:3",
    "\"Olhares altivos e coração orgulhoso, que é a lâmpada dos ímpios, são pecado.\" - Provérbios 21:4",
    "\"Os planos do diligente tendem à abundância, mas todo pressuroso certamente virá à pobreza.\" - Provérbios 21:5",
    "\"O ajuntar tesouros com língua falsa é vaidade que leva à morte os que buscam a morte.\" - Provérbios 21:6",
    "\"A rapina dos ímpios os destruirá, porquanto recusaram fazer justiça.\" - Provérbios 21:7",
    "\"O caminho do homem perverso é tortuoso, mas a obra do puro é reta.\" - Provérbios 21:8",
    "\"Melhor é morar num canto de telhado do que com a mulher ajuntadora em casa ampla.\" - Provérbios 21:9",
    "\"A alma do ímpio deseja o mal; o seu próximo não acha favor aos seus olhos.\" - Provérbios 21:10",
    "\"Quando o escarnecedor é castigado, o simples torna-se sábio; e, quando o sábio é instruído, recebe o conhecimento.\" - Provérbios 21:11",
    "\"O justo atenta para a casa do ímpio; a derrubados são os ímpios à ruína.\" - Provérbios 21:12",
    "\"O que tapa o seu ouvido ao clamor do pobre, também clamará e não será ouvido.\" - Provérbios 21:13",
    "\"O presente que se dá em oculto amansa a ira, e a dádiva no seio, a forte fúria.\" - Provérbios 21:14",
    "\"Para o justo é alegria o fazer justiça, mas destruição para os que praticam a iniquidade.\" - Provérbios 21:15",
    "\"O homem que anda desvia-se do caminho do entendimento na congregação dos mortos repousará.\" - Provérbios 21:16",
    "\"O que ama os prazeres passará necessidade; o que ama o azeite e o vinho nunca enriquecerá.\" - Provérbios 21:17",
    "\"O resgate do justo é o ímpio, e o transgressor fica em lugar do reto.\" - Provérbios 21:18",
    "\"Melhor é morar numa terra deserta do que com a mulher rixosa e iracunda.\" - Provérbios 21:19",
    "\"Tesouro desejável e azeite há na casa do sábio, mas o homem insensato os devora.\" - Provérbios 21:20",
    "\"O que segue a justiça e a benignidade achará a vida, a justiça e a honra.\" - Provérbios 21:21",
    "\"O sábio escala a cidade dos valentes, e derriba a fortaleza em que confiava.\" - Provérbios 21:22",
    "\"O que guarda a sua boca e a sua língua guarda a sua alma das angústias.\" - Provérbios 21:23",
    "\"Sobeba, arrogante, escarnecedor é o seu nome; o que procede com furor soberbo.\" - Provérbios 21:24",
    "\"O desejo do preguiçoso o mata, porque as suas mãos recusm trabalhar.\" - Provérbios 21:25",
    "\"Todo o dia cobiça cobiçou, mas o justo dá e não retém.\" - Provérbios 21:26",
    "\"O sacrifício dos ímpios é abominação; quanto mais trazê-lo com intenção maligna?\" - Provérbios 21:27",
    "\"A testemunha mentirosa perecerá, mas o homem que ouve falará sempre.\" - Provérbios 21:28",
    "\"O homem ímpio endurece o seu rosto; mas o reto atenta para o seu caminho.\" - Provérbios 21:29",

    // 351 a 400: Fechamento Exato com Mensagens Finais de Isaías, Salmos e Provérbios
    "\"Não há sabedoria, nem inteligência, nem conselho contra o Senhor.\" - Provérbios 21:30",
    "\"O cavalo prepara-se para o dia da batalha, mas a vitória vem do Senhor.\" - Provérbios 21:31",
    "\"O bom nome é antes de escolher do que as muitas riquezas; e a boa graça é melhor do que a prata e o ouro.\" - Provérbios 22:1",
    "\"O rico e o pobre se møem; a todos os fez o Senhor.\" - Provérbios 22:2",
    "\"O prudente prevê o mal, e esconde-se; mas os simples passam adiante, e sofrem a pena.\" - Provérbios 22:3",
    "\"O galardão da humildade e o temor do Senhor são riquezas, honra e vida.\" - Provérbios 22:4",
    "\"Espinhos e laços há no caminho do perverso; o que guarda a sua alma retira-se deles.\" - Provérbios 22:5",
    "\"Instrui o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele.\" - Provérbios 22:6",
    "\"O rico rege sobre os pobres, e o que toma emprestado é servo do que empresta.\" - Provérbios 22:7",
    "\"O que semeia a injustiça colherá a vaidade; e a vara da sua indignação falhará.\" - Provérbios 22:8",
    "\"O que tem os olhos generosos será abençoado, porque dá do seu pão ao pobre.\" - Provérbios 22:9",
    "\"Lança fora o escarnecedor, e a contenda se irá; e cessará a demanda e a vergonha.\" - Provérbios 22:10",
    "\"O que ama a pureza do coração, e tem a graça nos seus lábios, o rei será seu amigo.\" - Provérbios 22:11",
    "\"Os olhos do Senhor conservam a ciência, mas ele transtorna as palavras do transgressor.\" - Provérbios 22:12",
    "\"Diz o preguiçoso: Um leão está fora; serei morto no meio das ruas.\" - Provérbios 22:13",
    "\"Cova profunda é a boca das mulheres estranhas; aquele contra quem o Senhor se irá cairá nela.\" - Provérbios 22:14",
    "\"A estultícia está ligada ao coração da criança, mas a vara da correção a espantará dela.\" - Provérbios 22:15",
    "\"O que oprime o pobre para se engrandecer a si mesmo, e o que dá ao rico, certamente virá à pobreza.\" - Provérbios 22:16",
    "\"Inclina o teu ouvido, e ouve as palavras dos sábios, e aplica o teu coração ao meu conhecimento.\" - Provérbios 22:17",
    "\"Porque te será deleite se as guardares no teu ventre; fiquem juntas nos teus lábios.\" - Provérbios 22:18",
    "\"Para que a tua confiança seja no Senhor, to tenho a ti rotulado hoje, sim, a ti.\" - Provérbios 22:19",
    "\"Porventura não te tenho escrito excelentes coisas acerca dos conselhos e do conhecimento?\" - Provérbios 22:20",
    "\"Para fazer-te saber a certeza das palavras de verdade, para que possas dar respostas de verdade aos que te enviarem?\" - Provérbios 22:21",
    "\"Não roubes ao pobre, porque é pobre; nem oprimas ao aflito na porta;\" - Provérbios 22:22",
    "\"Porque o Senhor defenderá a causa deles, e despojará a alma dos que os despojam.\" - Provérbios 22:23",
    "\"Não tenhas amizade com o iracundo, nem andes com o homem colérico;\" - Provérbios 22:24",
    "\"Para que não aprendas as suas veredas, e apanhes um laço para a tua alma.\" - Provérbios 22:25",
    "\"Não sejas daqueles que se obrigam por mãos, e dos que ficam por fiadores de dívidas.\" - Provérbios 22:26",
    "\"Se não tens com que pagar, porque tirariam a tua cama de debaixo de ti?\" - Provérbios 22:27",
    "\"Não removas os antigos limites que teus pais puseram.\" - Provérbios 22:28",
    "\"Viste o homem diligente na sua obra? perante reis se estandartizará; não ficará diante dos obscuros.\" - Provérbios 22:29",
    "\"Ele dá força ao cansado, e multiplica as forças ao que não tem nenhum vigor.\" - Isaías 40:29",
    "\"Os jovens se cansam e se fatigam, e os mancebos caem tropeçando,\" - Isaías 40:30",
    "\"Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias; correrão, e não se cansarão; caminharão, e não se fatigarão.\" - Isaías 40:31",
    "\"Porque eu sou o Senhor teu Deus, que te seguro pela tua mão direita, e te digo: Não temas, eu te ajudo.\" - Isaías 41:13",
    "\"Portanto, não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.\" - Isaías 41:10",
    "\"Digo ao meu coração: O Senhor é a minha porção; por isso esperarei nele.\" - Lamentações 3:24",
    "\"Bom é o Senhor para os que esperam nele, para a alma que o busca.\" - Lamentações 3:25",
    "\"Bom é ter esperança, e aguardar em silêncio a salvação do Senhor.\" - Lamentações 3:26",
    "\"Porque o Senhor não rejeitará para sempre;\" - Lamentações 3:31",
    "\"Ainda que aniquile, terá compaixão segundo a multidão das suas misericórdias.\" - Lamentações 3:32",
    "\"Porque não aflije nem desampara de coração aos filhos dos homens.\" - Lamentações 3:33",
    "\"Esperei pacientemente no Senhor, e ele se inclinou para mim, e ouviu o meu clamor.\" - Salmos 40:1",
    "\"Tirou-me dum poço de perdição, duns lodaçais de lama, e pôs os meus pés sobre uma rocha, firmou os meus passos.\" - Salmos 40:2",
    "\"E pôs um novo cântico na minha boca, um hino ao nosso Deus; muitos o verão, e temerão, e confiarão no Senhor.\" - Salmos 40:3",
    "\"Bem-aventurado o homem que põe no Senhor a sua confiança, e não respeita os soberbos nem aos que se desviam para a mentira.\" - Salmos 40:4",
    "\"Muitas são, Senhor meu Deus, as maravilhas que tens operado para conosco, e os teus pensamentos não se podem contar diante de ti; se eu os quisesse anunciar, e falar deles, são mais do que se podem contar.\" - Salmos 40:5",
    "\"Sacrifício e oferta não quiseste; os meus ouvidos abriste; sacrifício e expiação pelo pecado não pediste.\" - Salmos 40:6",
    "\"Deleito-me em fazer a tua vontade, ó Deus meu; sim, a tua lei está dentro do meu coração.\" - Salmos 40:8",
    "\"A tua justiça não escondi dentro do meu coração; apregoei a tua fidelidade e a tua salvação. Não encobri a tua benignidade e a tua verdade da grande congregação.\" - Salmos 40:10"
];
